version: '3.1'
# To play with this file use following command: 
# $ docker-compose -f docker-compose.yml docker-compose.es.yml up 

services:
  web:
    environment: &webEnvironment
      DATABASE_URL: mysql://root:password@db/feder
      ELASTICSEARCH_URL: http://elasticsearch:9200/
      APACHE_TIKA_URL: 'http://tika:9998/'
      VIRUSTOTAL_API_KEY:
      ATTACHMENTSCANNER_API_KEY:
      ATTACHMENTSCANNER_API_URL:
      METADEFENDER_API_KEY:

  worker:
    command: python manage.py process_tasks
    environment: *webEnvironment

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      discovery.type: single-node
      cluster.routing.allocation.disk.threshold_enabled: 'false'
    ports:
      - "9200:9200"

  tika:
    image: quay.io/watchdogpolska/apache-tika