name: Python package

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  django:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: ${{ matrix.python }}
      DJANGO_VERSION: ${{ matrix.django }}
      METADEFENDER_API_KEY: ${{ secrets.METADEFENDER_API_KEY }}
    strategy:
      matrix:
        python: 
          - 3.6
          - 3.7
        django:
          - "==2.2.*"
          - "==3.0.*"
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Build application
      run: docker-compose build web
    - name: Migration check
      run: make check
    - name: Show settings
      run: make settings
    - name: Run test
      run: make test-es
#     - name: Send coverage report
#       run: make coverage_send
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    - name: Show MySQL logs
      run: docker-compose logs db
      if: failure()
    - name: Show Elasticsearch logs
      run: docker-compose logs elasticsearch
      if: failure()
    - name: Show Tika logs
      run: docker-compose logs tika
      if: failure()
    - name: Show docker process
      run: docker ps
      if: always()